lib/jsonapi/authorization/authorizing_operations_processor.rb, spec/dummy/app/controllers/tags_controller.rb, spec/dummy/app/models/article.rb, spec/dummy/app/models/comment.rb, spec/dummy/app/models/tag.rb, spec/dummy/app/policies/tag_policy.rb, spec/dummy/app/resources/article_resource.rb, spec/dummy/app/resources/comment_resource.rb, spec/dummy/app/resources/tag_resource.rb, spec/dummy/config/routes.rb, spec/dummy/db/migrate/20160125083537_create_models.rb, spec/dummy/db/schema.rb, spec/fixtures/articles.yml, spec/fixtures/tags.yml, spec/requests/related_resources_operations_spec.rb, spec/requests/relationship_operations_spec.rb, spec/requests/resource_operations_spec.rb, spec/requests/tricky_operations_spec.rb
Discussed on https://github.com/venuu/jsonapi-authorization/pull/10#issuecomment-181308985
(Edit by @valscion: Closes #13)
=> Add support for custom primary key on related_models

lib/jsonapi/authorization/authorizing_operations_processor.rb, lib/jsonapi/authorization/default_pundit_authorizer.rb, spec/dummy/app/models/article.rb, spec/dummy/app/models/comment.rb, spec/dummy/app/models/user.rb, spec/dummy/app/resources/article_resource.rb, spec/dummy/app/resources/user_resource.rb, spec/dummy/db/migrate/20160125083537_create_models.rb, spec/dummy/db/schema.rb, spec/fixtures/articles.yml, spec/fixtures/comments.yml, spec/fixtures/users.yml, spec/jsonapi/authorization/default_pundit_authorizer_spec.rb, spec/requests/included_resources_spec.rb, spec/requests/resource_operations_spec.rb, spec/support/authorization_stubs.rb
Closes #7 
Logics to implement:
Attach those logics to all the end points which return records:
*  [x] `POST /resources`
Review notes:
=> Authorize included resources

README.md, lib/jsonapi/authorization/configuration.rb, lib/jsonapi/authorization/default_pundit_authorizer.rb, lib/jsonapi/authorization/pundit_scoped_resource.rb, spec/dummy/config/application.rb, spec/dummy/db/schema.rb, spec/jsonapi/authorization/configuration_spec.rb
* Added tests
* Defaults to :user for backwards combat
* Can specify a symbol or a proc
* Updated README
```ruby
JSONAPI::Authorization.configure do |config|
config.pundit_user = :current_user
config.pundit_user = ->(context){ context[:current_user] }
config.pundit_user = ->(context){ context }
end
```
=> Added ability to custom pundit_user

README.md, lib/jsonapi/authorization/authorizing_processor.rb, lib/jsonapi/authorization/default_pundit_authorizer.rb, spec/dummy/app/policies/article_policy.rb, spec/jsonapi/authorization/default_pundit_authorizer_spec.rb, spec/requests/relationship_operations_spec.rb
This PR is to discuss a proposal for how the authorization of relationships could be handled (see #30).
=> Authorize relationship actions with custom policy methods

spec/jsonapi/authorization/default_pundit_authorizer_spec.rb, spec/support/pundit_stubs.rb
We want to make sure the tests for the new cases match all the possible cases:
* authorized with finer grained policy but NOT authorized with `update?`
* NOT authorized with finer grained policy but authorized with `update?`
* authorized with both finer grained policy and `update?`
* :point_up: This also means that the current tests could be merged together
I needed to do some refactoring with the stubbing logic to make it work correctly for all these cases.
=> Add tests for every scenario of the relationship operations

.travis.yml, Gemfile
Oops :flushed: Seems like #34 was seriously broken as it disabled running the specs in CI, too 😰
=> Fix travis not running specs

lib/jsonapi/authorization/authorizing_processor.rb, lib/jsonapi/authorization/default_pundit_authorizer.rb, spec/jsonapi/authorization/default_pundit_authorizer_spec.rb, spec/requests/tricky_operations_spec.rb
FYI: This breaks tests. I haven't had time to fix them, but wanted to just put this code out to start discussion in the mean time.
This will check permissions on new records being added. It uses the same method syntax as @matthias-g's #40 recently merged PR. i.e. `add_comment`, `remove_comment`, `add_to_users`, `remove_from_users`, etc. It also creates a new method syntax for polymorphic source records. 
For example, if comments are polymorphic, in the comment policy you could check if the user has permissions to comment on an article with `add_commentable_article?(article)`. This would cover payloads like:
```
data: {
type: 'comment,
attributes: {
...
},
relationships: {
commentable: {
data: { type: 'articles', id: 1 }
}
}
...
}
```
Also, the `remove_to_one_relationship` method was not …
=> Handling relationship policy checking in replace_fields

spec/jsonapi/authorization/default_pundit_authorizer_spec.rb
- Test scenarios where `replace_<type>?` is not defined for related records, not when user is authorized and unauthorized to `update?` source record.
As requested by @valscion at the end of issue #51's comments.
=> Add spec for missing #replace_fields scenario

lib/jsonapi/authorization/default_pundit_authorizer.rb, spec/dummy/app/policies/article_policy.rb, spec/jsonapi/authorization/default_pundit_authorizer_spec.rb
We seem to have missed a test case for the `related_records_with_context` cases and so have got this bug. Credits to @nbarthel for discovering this case in #65, thanks!
Closes #65
=> Fix create_resource authorization breaking with has_one association

lib/jsonapi/authorization/default_pundit_authorizer.rb, spec/jsonapi/authorization/default_pundit_authorizer_spec.rb
This was the functionality present before v1.0.0 and should be kept intact. It is what we want to do — changes to relationships can be though as changing the related records.
It seems that at some point, this functionality got accidentally lost. The change seems to date to https://github.com/venuu/jsonapi-authorization/pull/51
Seems like the reason this slipped through the cracks was that we didn't remember to check these cases back when relationship operation authorization was implemented in #40, so when #51 used the same methods, the old functionality accidentally got lost.
=> Fall back to authorizing update? on related records

lib/jsonapi/authorization/authorizing_processor.rb, spec/requests/relationship_operations_spec.rb
This PR picks off from #53 and adds authorization for the replacing of a polymorphic has-one relationship.
Seems like `jsonapi-resources` is broken and won't allow clearing of a polymorhpic has-one relationship by sending
`PATCH /tags/1/relationships/taggable`
```
{ "data": null }
```
The issue upstream is here: https://github.com/cerebris/jsonapi-resources/issues/1081
I skipped the tests for the relationship nullification for now.
=> Authorize replacing of a polymorphic has-one relationship

lib/jsonapi/authorization/authorizing_processor.rb, lib/jsonapi/authorization/pundit_scoped_resource.rb
This fixes #80
It seems to be that JR always passes a hash to the `relation_name` accessors, with the `context` under key `:context`
https://github.com/cerebris/jsonapi-resources/blob/v0.9.0/lib/jsonapi/resource.rb#L250
Let's just use that everywhere in `jsonapi-authorization`, too.
It's a bit odd that JR passes way more information down the same `relation_name` when in the scope of processor, but that doesn't seem to be important to us. Documentation only refers to fetching the `context` from the options, and AFAICT, doesn't tell about what else is in the options hash:
http://jsonapi-resources.com/v0.9/guide/resources.html#Options
```rb
class BookResource < JSONAPI::Resource
has_many :book_comments, relation_name: -> (options = {}) {
context = options[:context]
current_user = context ? …
```
=> Fix relation_name lambda being broken

.rubocop.yml, lib/jsonapi/authorization/authorizing_processor.rb, lib/jsonapi/authorization/default_pundit_authorizer.rb, spec/jsonapi/authorization/default_pundit_authorizer_spec.rb, spec/requests/included_resources_spec.rb, spec/requests/related_resources_operations_spec.rb, spec/requests/relationship_operations_spec.rb, spec/requests/resource_operations_spec.rb, spec/requests/tricky_operations_spec.rb, spec/support/authorization_stubs.rb
I saw in #48 that help was wanted using keyword args for `JSONAPI::Authorization::DefaultPunditAuthorizer` so I've had a go at it. I've done 2 methods to see how it goes, and I'd like feedback to check I'm doing what you wanted before continuing. 
The only hard part I found was making the `AuthorizationStubs` helpers work with keyword args as well as splat args. I'm not entirely happy with how I solved that, so any thoughts on that would be great. To see why I've done that, try changing the stub method and re-run the tests and you'll find a lot of things start breaking in various places with wrong-number-of-argument errors and other fun things.
=> Default pundit authorizer keyword args

.travis.yml, jsonapi-authorization.gemspec
Seems like CI is failing because Travis is using bundler v2:
https://travis-ci.org/venuu/jsonapi-authorization/jobs/415322974#L468
=> Fix CI caused by Bundler v2

Appraisals, gemfiles/rails_4_2_pundit_1.gemfile, gemfiles/rails_4_2_pundit_2.gemfile, gemfiles/rails_5_0_pundit_1.gemfile, gemfiles/rails_5_0_pundit_2.gemfile, gemfiles/rails_5_1_pundit_1.gemfile, gemfiles/rails_5_1_pundit_2.gemfile, gemfiles/rails_5_2_pundit_1.gemfile, gemfiles/rails_5_2_pundit_2.gemfile, spec/dummy/app/controllers/taggable_controller.rb, spec/dummy/app/resources/taggable_resource.rb
This should make tests use the latest 0.9 release of `jsonapi-resources`, which at the time of writing, is v0.9.4: https://github.com/cerebris/jsonapi-resources/releases/tag/v0.9.4
=> Relax jsonapi-resources to ~> 0.9 in tests

jsonapi-authorization.gemspec
Try to fix travis by downgrading sqlite. It gives an error in travis that SQLite 1.3.6 cannot be actived, but that 1.4.0 is already activated. So I quess that downgrading it to 1.3.6 will fix it.
Travis error:
`can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0.`
Fixes #114
=> Downgrade sqlite

.travis.yml
Seems like the steps done in https://github.com/venuu/jsonapi-authorization/pull/107 are now broken.
=> Fix CI again caused by Bundler v2

lib/jsonapi/authorization/authorizing_processor.rb, spec/requests/included_resources_spec.rb, spec/requests/relationship_operations_spec.rb, spec/requests/tricky_operations_spec.rb
Fixes https://github.com/venuu/jsonapi-authorization/issues/118
This PR fixes a bug where related resources are not checked for authorization if they are not in the user's scope.
Also fixes inconsistencies between the behavior of has-one, has-many, and polymorphic relationships to always return a 404 instead of sometimes returning a 403 when the user should not be able to see that a given record exists.
=> Check for authorization against related records

README.md
Also relax the exact numbering on JR 0.9 support.
These changes hopefully clarify how we got quite quickly from [v1.0.0](https://github.com/venuu/jsonapi-authorization/releases/tag/v1.0.0) to [v2.0.0](https://github.com/venuu/jsonapi-authorization/releases/tag/v2.0.0), and how it's likely we'll soon get to v3.0.0 once https://github.com/venuu/jsonapi-authorization/pull/119 is merged.
=> Clarify versioning and link to changelogs in README.md

lib/jsonapi/authorization/authorizing_processor.rb, spec/requests/included_resources_spec.rb, spec/requests/tricky_operations_spec.rb
Fixes a bug introduced in https://github.com/venuu/jsonapi-authorization/pull/119
Any has-one relationship authorizers e.g. `ArticlePolicy#create_with_author?(author)` are currently breaking since the default authorizer is calling the method with `[author]` instead of `author`.
I was trying to be too clever in that PR simplifying code and didn't realize that there may be code elsewhere that relied on has-one relationships sending related records back as an actual record instead of potentially a single-object array.
I'd like to add a spec to cover this case since there are no (non-stub setup reliant) specs covering this behavior, but am unsure how to structure it. I believe this can go out on its own now, or am happy to take some feedback as to where to add a test for this.
While there was …
=> Fix a bug with has-one relationship authorizers

.gitignore, Appraisals, gemfiles/rails_4_2_pundit_1.gemfile, gemfiles/rails_4_2_pundit_2.gemfile, gemfiles/rails_5_0_pundit_1.gemfile, gemfiles/rails_5_0_pundit_2.gemfile, gemfiles/rails_5_1_pundit_1.gemfile, gemfiles/rails_5_1_pundit_2.gemfile, gemfiles/rails_5_2_pundit_1.gemfile, gemfiles/rails_5_2_pundit_2.gemfile, jsonapi-authorization.gemspec
The version constraint was too relaxed, as `jsonapi-authorization` does not yet work with JR v0.10.0 — see #64 for more details.
=> Enforce no support for JR v0.10.0 yet in gemspec

spec/jsonapi/authorization/default_pundit_authorizer_spec.rb
While attempting to run specs to investigate compatibility with JR `v0.10.0`, I ran into several failures with the newly released `rspec-expectations` `v3.8.5`
https://github.com/rspec/rspec-expectations/pull/1125 removed the ability to use implicit block expectations
=> Remove implicit block expectation syntax

.travis.yml, Appraisals, gemfiles/rails_4_2_pundit_1.gemfile, gemfiles/rails_4_2_pundit_2.gemfile, gemfiles/rails_5_0_pundit_1.gemfile, gemfiles/rails_5_0_pundit_2.gemfile, gemfiles/rails_5_1_pundit_1.gemfile, gemfiles/rails_5_1_pundit_2.gemfile, gemfiles/rails_5_2_pundit_2.gemfile, gemfiles/rails_6_0_pundit_1.gemfile, gemfiles/rails_6_0_pundit_2.gemfile, jsonapi-authorization.gemspec, spec/dummy/app/controllers/application_controller.rb, spec/dummy/app/controllers/articles_controller.rb, spec/dummy/app/controllers/comments_controller.rb, spec/dummy/app/controllers/tags_controller.rb, spec/dummy/app/controllers/users_controller.rb
Loosens the `sqlite3` dev dependency to allow tests to run on any supported version of rails.
Adds appraisals and gemfiles for rails 6 to run in CI
Updates the ruby version in CI to 2.5
Resolves #132
=> Run CI against Rails 6

README.md
This repository has been migrated from the old https://travis-ci.org to https://travis-ci.com and is now running with the Travis GitHub application.
Let's see if this brings better status checks to pull requests :relaxed:
=> Update build badge to point to travis-ci.com

spec/support/custom_matchers.rb
This way test failures will show what the HTTP status code actually was when test fails as well as output the entire response body. The response body will most likely contain vital debugging information to help figure out why the test failed.
This was cherry-picked from a commit I did to https://github.com/venuu/jsonapi-authorization/pull/131 as this will be useful to all the future changes done to this gem.
=> Add better debuggability to be_X test failures
